- docs/openebs-operator-0.8.1.yaml
NDM version has been updated from 0.3.0 to 0.3.1 for OpenEBS 0.8.1 release.
> Update NDM image tag from v0.3.0 to v0.3.1

- docs/openebs-operator-susecaas.yaml
- Add clusterrole for running NDM in susecass paltform
- change the mount path of NDM to directory which has read and write access
`/var/lib/overlay/openebs/sparse`
- Add a env variable OPENEBS_IO_CSTOR_POOL_SPARSE_DIR in maya-apiserver deployment
```
- name: OPENEBS_IO_CSTOR_POOL_SPARSE_DIR
value: "/var/lib/overlay/openebs/sparse"
```
Signed-off-by: inyee786 <intakhab.ali@mayadata.io>
> Feat(Docs) Add OpenEBS operator for SUSECaas Platform

- docs/openebs-operator-0.8.2.yaml
- update ndm version to v0.3.5. 
- mount `/proc` directory instead of `/proc/1/mounts` file
> chore(ndm) : update ndm version to v0.3.5

- docs/openebs-operator-arm-dev.yaml
although pgrep -f .*localpv return 1 in the container, liveliness probe still fail and will cause the pod restart.
Fixes openebs/openebs#2712
Signed-off-by: wangzihao <wangzihao18@huawei.com>
> fix(arm): Modify pgrep argument in localpv liveliness of arm version

- docs/openebs-operator-1.6.0-aws.yaml
- Add openebs operator YAML for making the availability of 1.6.0 in AWS market place
Notes to the reviewer:
The following is  the change from 1.5.0-aws-operator yaml spec apart from ECR registry details and OPENEBS_IO_INSTALLER_TYPE.
- Added "cstorvolumepolicies" under clusterrole
> feat(YAML): Add operator YAML for 1.6.0 in AWS

- docs/openebs-operator-1.7.0-aws.yaml
Add openebs operator YAML for making the availability of 1.7.0 in AWS market place
**Notes to the reviewer:**
The following are the changes compared to 1.6 AWS
- Update ECR registry of images with new container group
- Create new CRs section for "poddisruptionbudgets" and add more rules.
- Add ENV variable for basepath creation  and volumemount for dumping core for NDM
> feat(YAML): Add operator YAML for 1.7.0 in AWS

- docs/openebs-operator-1.1.0.yaml
commit changes the failure policy to Ignore to ignore the invalid certificates which is deprecated and no longer in use by the admission webhook from 1.4.0 onwards.
**Note** : We already using Failure policy as `Ignore` in 1.2.0 and so forth
Signed-off-by: prateekpandey14 <prateekpandey14@gmail.com>
> fix(operator): update operator-1.1.0 with Ignore webhook failure policy

- scripts/jiva-tools/check_jiva_replica_images.sh
This script counts the chain length and compares it with the number of .img and .img.meta files
If there is difference in the counts, it displays the same
Please note that this script doesn't modify anything on the disk
It reads *.img.meta files, and performs find command
Signed-off-by: Vitta <vitta@mayadata.io>
> script(jiva): compares chain len with number of img, meta files

- scripts/jiva-tools/jiva_preupgrade_checks.sh
Printing the used size of the snapshots/volume will make it easy to compare how much data difference is there between the replicas without comparing the lunmaps.
> script(jiva): Add command to print the used snapshot size

- scripts/jiva-tools/README.md
- scripts/jiva-tools/jiva_preupgrade_checks.sh
This PR removes unnecessary prints when running jiva preupgade checks script.
With these changes, output in positive case looks like:
```
Total used size: 0
ChainLen:1
img files count:1
meta files count:1
No discrepancies found among the files in this replica
```
Signed-off-by: Vitta <vitta@mayadata.io>
> fix(jiva-tool): remove unnecessary prints

- docs/openebs-operator-1.9.0-aws.yaml
- Remove extra image tag for some of the OpenEBS components which makes the pods in ErrImagepull state for AWS 1.9 version
> fix(YAML): Remove extra image tag

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/lint-test.yaml
- README.md
- ct.yaml
- stable/.helmignore
- stable/openebs/Chart.yaml
- stable/openebs/OWNERS
- stable/openebs/README.md
- stable/openebs/templates/NOTES.txt
- stable/openebs/templates/_helpers.tpl
- stable/openebs/templates/clusterrole.yaml
- stable/openebs/templates/clusterrolebinding.yaml
- stable/openebs/templates/cm-node-disk-manager.yaml
- stable/openebs/templates/daemonset-ndm.yaml
- stable/openebs/templates/deployment-admission-server.yaml
- stable/openebs/templates/deployment-local-provisioner.yaml
- stable/openebs/templates/deployment-maya-apiserver.yaml
- stable/openebs/templates/deployment-maya-provisioner.yaml
- stable/openebs/templates/deployment-maya-snapshot-operator.yaml
- stable/openebs/templates/deployment-ndm-operator.yaml
- stable/openebs/templates/psp-clusterrole.yaml
- stable/openebs/templates/psp-clusterrolebinding.yaml
- stable/openebs/templates/psp.yaml
- stable/openebs/templates/service-maya-apiserver.yaml
- stable/openebs/templates/serviceaccount.yaml
- stable/openebs/values.yaml
Changes add stable 1.9.0 openebs helm charts with automated chart tests which deploys the kind based kubernetes cluster and deploy the charts
Runing tests results be cheked [here](https://github.com/prateekpandey14/charts-2/runs/611392363?check_suite_focus=true)
> feat(charts): add stable 1.9.0 openebs helm charts with automated chart tests

- stable/openebs/Chart.yaml
- stable/openebs/templates/deployment-ndm-operator.yaml
**What this PR does / why we need it:**
PR add a SERVICE_ACCOUNT environment in ndm-operator
deployment. This is required for running the cleanup
jobs in clusters with PodSecurityPolicies enabled/
Openshift Clusters.
sync PR: https://github.com/helm/charts/pull/22136
> [stable/openebs]: add service account in NDM operator

- stable/openebs/README.md
- stable/openebs/templates/deployment-maya-apiserver.yaml
- stable/openebs/templates/deployment-ndm-operator.yaml
- stable/openebs/values.yaml
change key to enable/disable crd installation
Signed-off-by: akhilerm <akhil.mohan@mayadata.io>
This PR syncs the key/value of crd installation with upstream helm
> [stable/openebs]: change crd installation enable/disable key

- docs/openebs-operator-arm-dev.yaml
Signed-off-by: Nick Pappas <nick@radicand.org>
The current version of the ARM operator contains a reference to the standard/amd64 version of m-apiserver. This PR corrects the reference to point to the arm64 image.
- [-] Chart Version bumped
- [-] Variables are documented in the README.md
- [-] Title of the PR starts with chart name (e.g. `[stable/openebs]`)
> [arm-operator] fix: m-apiserver image now points to arm64 repo

- .github/workflows/release.yaml
This uses `helm/chart-releaser-action` to turn your GitHub project into a self-hosted Helm chart repo. It does this, during every push to master – by checking each chart in your project, and whenever there's a new chart version, creates a corresponding GitHub release named for the chart version, adds Helm chart artifacts to the release,and creates or updates an index.yaml file with metadata about those releases, which is then hosted on GitHub Pages
A project Secret named CR_TOKEN with the value of a [GitHub personal access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token) needs to be created:
- The token must have repo scope
- The token's user must have write access to the project
Signed-off-by: …
> feat(build): add helm releaser github action to manage chart releases

- charts/openebs/Chart.yaml
- charts/openebs/values.yaml
For cluster operators who also run ceph within the cluster, this will stop /dev/rbd[0-9]+ devices being accidentally added as a block device
> [stable/openebs] Add rbd to exclusions

- scripts/release/create_changelog_pr.sh
Changes:
-   Added a script to generate changelog for a tag and raise a PR in production/release branch
Script Manual: 
```
Usage:
./create_changelog_pr.sh <options> TAG-NAME
Example:
./create_changelog_pr.sh -r github-org/repo-name v1.1.0-RC1
TAG-NAME is required to execute this script.
Repo Name(-r) is required for github PR link. If it is not mentioned then generated PR link will not work.
Supported options are as below. Mandatory arguments to long options are mandatory for short options too:
-h, --help                              Show this message and exit
-r, --repo REPO                         Github repo, in org/repo format.
To raise a PR, this option is mandatory.
If mentioned PR will be created in this repo.
Example:
-r openebs/plugin
--repo openebs/plugin
-p, …
```
> feat(release): script to generate changelog for tag and raise a PR

- kubelet-restart.yaml
This can help to restart kubelet on Mayastor storage nodes. Manually verified that it works. 
> (mayastor) : Kubelet-restart helps restarting kubelets on msn

- 1.12.0/openebs-operator-1.12.0-RC1.yaml
- use multiarch ndm image
- default to docker hub, since quay does not support multiarch images.
> chore(yaml): fix ndm architecture and remove quay registry

- charts/openebs/Chart.yaml
- charts/openebs/README.md
- charts/openebs/templates/deployment-admission-server.yaml
- charts/openebs/values.yaml
This is added because in EKS there's some wierd network stuff that makes it necessary. See [this](https://docs.projectcalico.org/getting-started/kubernetes/managed-public-cloud/eks) the note at **Install EKS with Calico networking**. The extract is:
> Note: Calico networking cannot currently be installed on the EKS control plane nodes. As a result the control plane nodes will not be able to initiate network connections to Calico pods. (This is a general limitation of EKS’s custom networking support, not specific to Calico.) As a workaround, trusted pods that require control plane nodes to connect to them, such as those implementing admission controller webhooks, can include hostNetwork:true in their pod spec. See the Kuberentes API pod spec definition for more information on this setting. …
> [stable/openebs] Add support to admission server to use hostNetwork

- 1.12.0/openebs-operator-1.12.0-aws.yaml
- openebs-operator-aws.yaml
Changes from 1.11.0 AWS YAML spec:
------
- openebs.io/version to `1.12.0`
- Update image for all 15 repositories with new container group `cg-1793225711`
- Add `ADMISSION_WEBHOOK_FAILURE_POLICY` as `Fail` for admission-webhook
- Changes in image repository name of `node-disk-operator-amd64` to `node-disk-operator`
- moved away from quay repository and adding images to docker hub
- [ x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x ] Title of the PR starts with chart name (e.g. `[stable/openebs]`)
> [openebs]chore(release): add OpenEBS 1.12.0 YAML for AWS

- charts/openebs/Chart.yaml
- charts/openebs/templates/deployment-admission-server.yaml
Update the admission server deployment template imagePull Policy to use from values.yaml instead of hardcoded value.
Required in case of air gapped environments
fixes: #131 
> [stable/openebs]: remove hardcoded admission deployment imagePullPolicy

- scripts/release/buildscripts/push
This PR fixes the push script for builds in openebs to remove the leading v from the image tags.
> fix(build): trim v from all image tags

- 2.0.0/cstor-operator-2.0.0-RC1.yaml
- 2.0.0/cstor-operator-2.0.0-RC2.yaml
- 2.0.0/cstor-operator.yaml
- 2.0.0/ndm-operator.yaml
This PR adds following operator yamls
- Add cstor operator 2.0.0-RC1 yaml
- Add cstor operator 2.0.0-RC2 yaml
- Add cstor operator 2.0.0 yaml
- Add ndm-operator 0.8.0 yaml(Which will be helpful to users installing only new cStor)
- Verified changes locally
> chore(operator, yaml): add cstor operator 2.0.0

- 2.0.0/openebs-operator-2.0.0-aws.yaml
- openebs-operator-aws.yaml
Changes from 1.12.0 AWS YAML spec:
------
- openebs.io/version to `2.0.0`
- Enabled NDM feature gate for "GPTBasedUUID" by default
-  Added a new directory(/dev) to mount it inside the container to read the mount point of devices and partition information.
> [openebs]chore(release): add OpenEBS 2.0.0 YAML for AWS

- 2.0.0/openebs-operator-2.0.0-aws.yaml
- openebs-operator-aws.yaml
Wrong image mentioned for Node disk manager image. Updated with correct one.
> [openebs]fix(release): OpenEBS 2.0.0 YAML for AWS

- openebs-operator-arm-dev.yaml
openebs/linux-utils is multiarch so it should not have openebs/linux-utils-arm64 in the name
> Switch openebs/linux-utils to multiarch

- charts/openebs/Chart.yaml
- charts/openebs/README.md
- charts/openebs/values.yaml
- update NDM version to 0.9.1 to fix for a container crash bug
> [stable/openebs]: update NDM version to 0.9.1

- README.md
Mayastor published an initial version of its Helm chart. It is currently maintained within the same repository. This patch just adds a note to README.
(closes #168)
> Add location of the Mayastor Helm chart

- charts/openebs/Chart.yaml
- charts/openebs/README.md
- charts/openebs/templates/daemonset-ndm.yaml
- charts/openebs/templates/deployment-admission-server.yaml
- charts/openebs/templates/deployment-local-provisioner.yaml
- charts/openebs/templates/deployment-maya-apiserver.yaml
- charts/openebs/templates/deployment-maya-provisioner.yaml
- charts/openebs/templates/deployment-maya-snapshot-operator.yaml
- charts/openebs/templates/deployment-ndm-operator.yaml
- charts/openebs/values.yaml
The PR should be squashed and merged.
> [stable/openebs]: update openebs charts to 2.4.0

- 2.4.0/openebs-operator-arm-dev.yaml
- 2.4.0/openebs-operator.yaml
- openebs-operator-arm-dev.yaml
- openebs-operator.yaml
Ref: https://github.com/openebs/openebs/issues/3226
With https://github.com/openebs/external-storage/pull/128, a new
configuration option is provided to enable/disable the setting
of node affinity on jiva replica deployments.
This PR provides an example on how to configure the ENV
variable on the openebs provisioner.
Signed-off-by: kmova <kiran.mova@mayadata.io>
> feat(operators): example config for jiva node affinity

- charts/openebs/Chart.yaml
- charts/openebs/README.md
- charts/openebs/values.yaml
update openebs k8s provisioner to 2.4.1 to add support for kubernetes 1.20
> [stable/openebs]: update openebs k8s provisioner to 2.4.1

- 2.4.0/openebs-operator-arm-dev.yaml
- 2.4.0/openebs-operator.yaml
- openebs-operator-arm-dev.yaml
- openebs-operator.yaml
- update openebs-k8s-provisioner to 2.4.1 to work on kubernetes 1.20
> fix(operator):  update openebs provisioner to 2.4.1

- examples/local-device/local-device-pvc.yaml
change localpv device storage class name to `openebs-device` in samples
Ref: https://github.com/openebs/openebs/issues/3312#issuecomment-745260953
> fix(yaml):fix localpv storage class in sample yaml

- grafana-charts/README.md
- grafana-charts/Storagepooldashboard.json
- grafana-charts/clustervolumesdashboard.json
- grafana-charts/cstorvolumereplicasdashboard.json
- grafana-charts/localpvdashboard.json
- grafana-charts/storageclassvolumedashboard.json
- grafana-charts/storagepoolclaimdashboard.json
- grafana-charts/storagepooldashboard.json
- grafana-charts/volumetiledviewdashboard.json
- grafana-charts/volumeworkloadreportdashboard.json
The following grafana dashboards for volumes and pools are added:
1. clustervolumesdashboard
2. cstorvolumereplicasdashboard
3. localpvdashboard
4. storagepoolclaimdashboard
5. storageclassvolumedashboard
6. Storagepooldashboard
7. volumetiledviewdashboard
8. volumeworkloadreportdashboard
Refer the following doc for details regarding the dashboards: https://docs.google.com/document/d/1hM9jaPX8OUoAx4exklJq0pLxgvvf-Hh4BJLaZ8V2bFs/edit
> Added grafana charts for pools and volumes

- microk8s-cstor-operator.yaml
Add microsk8s based cstor operator yaml ,where the `root-dir` is not `/var/lib/kubelet/` and configured as for example `/var/snap/microsk8s/common/var/lib/kubelet` .
Here we are creating a new operator file , which has updated volume and its mounts according to the root-dir path
> refact(cstor): add microk8s based cstor operator yaml

- charts/openebs/Chart.yaml
- charts/openebs/templates/cleanup-webhook.yaml
- charts/openebs/values.yaml
This PR addresses the issue: https://github.com/openebs/openebs/issues/3383
The solution is based on looking into other projects with similar webhook related problems ref: https://github.com/Kong/gcp-marketplace/blob/main/GKE/Kuma/chart/templates/pre-delete-webhooks.yaml
> fix(helm): replace deprecated hyperkube image in pre-delete hook

- charts/openebs/Chart.yaml
- charts/openebs/README.md
- charts/openebs/templates/cleanup-webhook.yaml
- charts/openebs/values.yaml
This PR makes the cleanup pre delete hook job image configurable for air-gap setups
> refact(charts): make cleanup pre hook image configurable

- charts/openebs/Chart.yaml
- charts/openebs/README.md
- charts/openebs/templates/cleanup-webhook.yaml
- charts/openebs/values.yaml
- update values
- update dependency charts
- fix indentation in webhook cleanup template
> [stable/openebs]: update helm chart to 2.10.0

- charts/openebs/Chart.yaml
- charts/openebs/templates/cleanup-webhook.yaml
- charts/openebs/values.yaml
Cleanup job fails if the validatingwebhookconfiguration is deleted beforehand. This stalls helm chart remove. Eventually leads to timeout. Fixed it with a OR clause.
> fix(cleanup-job): add OR clause to prevent job from failing

- .github/workflows/lint-test.yaml
- charts/openebs/Chart.yaml
- charts/openebs/README.md
- charts/openebs/values.yaml
This PR updates the helm chart to pull v2.10.1 of openebs-localpv/localpv-provisioner dependent chart. 
Then PR requires https://github.com/openebs/dynamic-localpv-provisioner/pull/66 to be merged.
> fix(charts): Update provisioner-localpv image to 2.10.1

- charts/openebs/Chart.yaml
Bump cstor chart version 2.11.0 -> 2.11.2
Bump lvm localpv chart version 0.7.0 -> 0.7.1
> chore(helm): bump cstor and lvm localpv version

- charts/openebs/Chart.yaml
- charts/openebs/README.md
- charts/openebs/values.yaml
Update openebs/openebs helm chart with dynamic-localpv-provisioner items...
1. provisioner-localpv image version (v2.11.1)
2. dependent helm chart version (v2.11.1)
Update openebs/openebs helm chart with jiva-operator item...
1. dependent helm chart version (v2.11.1)
Ref: https://github.com/openebs/dynamic-localpv-provisioner/issues/71
Depends on 
https://github.com/openebs/dynamic-localpv-provisioner/pull/72
https://github.com/openebs/jiva-operator/pull/119
> chore(charts): Update openebs/openebs helm chart for dynamic-localpv and jiva-operator v2.11.1

- 2.11.0/openebs-operator-lite.yaml
- openebs-operator-lite.yaml
This fixes a typo in the openebs-operator-lite.yaml file (v2.11.0). 
YAML end of directive marker between openebs-ndm-operator and openebs-localpv-provisioner deployments had too many '-' characters.
> Fix(openebs-operator-lite): Fix typo in openebs-operator-lite.yaml

- charts/openebs/Chart.yaml
- charts/openebs/README.md
- charts/openebs/templates/deployment-admission-server.yaml
- charts/openebs/templates/deployment-maya-apiserver.yaml
- charts/openebs/templates/deployment-maya-provisioner.yaml
- charts/openebs/templates/deployment-maya-snapshot-operator.yaml
- charts/openebs/templates/service-maya-apiserver.yaml
- charts/openebs/values.yaml
Add a flag to control legacy components installation. Default value is true, so by default legacy components will be installed.
Use - `--set legacy.enabled=false` to disable legacy components.
Fix - https://github.com/openebs/charts/issues/235
> feat(charts): add flag to control legacy components installation

- charts/openebs/Chart.yaml
- charts/openebs/templates/cm-node-disk-manager.yaml
- charts/openebs/templates/daemonset-ndm.yaml
- charts/openebs/templates/deployment-local-provisioner.yaml
- charts/openebs/templates/deployment-ndm-operator.yaml
Remove mutually exclusive flags ie -
When ndm is installed using openebs-ndm chart then disable local templates. When local pv is installed using localpv-provisioner then disable local templates. fix - https://github.com/openebs/charts/issues/245
This will change the installation command from
```bash
helm install openebs openebs/openebs --namespace openebs --create-namespace \
--set localprovisioner.enabled=false \
--set ndm.enabled=false \
--set ndmOperator.enabled=false \
--set openebs-ndm.enabled=true \
--set legacy.enabled=false \
--set localpv-provisioner.enabled=true
```
to
```bash
helm install openebs openebs/openebs --namespace openebs --create-namespace \
--set legacy.enabled=false \
--set localpv-provisioner.enabled=true
--set openebs-ndm.enabled=true \
```
> feat(charts): remove mutually exclusive flags

- charts/openebs/Chart.yaml
- charts/openebs/README.md
- charts/openebs/templates/cleanup-webhook.yaml
openebs-webhook-cleanup job attempts to cleanup openebs-validating-webhook-cfg even when legacy.enabled=false is set.
Correcting the condition.
README.md changes to update the installation commands for cStor-CSI, Jiva-CSI, ZFS-LocalPV, LVM-LocalPV, LocalPV-Hostpath-and-Device.
> fix(chart): Disable openebs webhook cleanup when legacy.enabled=false

- jiva-operator.yaml
- versioned/2.12.0/jiva-operator.yaml
This PR updates the CRDs and images for jiva-operator to 2.12.2
> refact(charts): update jiva operator to 2.12.2

- legacy-openebs-operator.yaml
- openebs-operator.yaml
- versioned/2.12.0/openebs-operator.yaml
2.12.1 maya-apiserver image no longer creates LocalPV storageclasses.
This PR uses 2.12.1 maya-apiserver. Creates LocalPV storageClasses openebs-hostpath and openebs-device using YAMLs.
Bumped 2.12.0 to 2.12.1 in openebs.io/version labels throughout.
---------------------
Bumped all image tag (except openebs/jiva) to 2.12.1
Bumped openebs/jiva image tag to 2.12.2.
This depends on openebs/maya#1816
Ref: https://github.com/openebs/dynamic-localpv-provisioner/issues/90
> chore(openebs-operator): create LocalPV storageClasses using YAMLs

- charts/openebs/Chart.yaml
- charts/openebs/templates/localprovisioner/device-class.yaml
- charts/openebs/templates/localprovisioner/hostpath-class.yaml
Changes in #257 adds an extra newline to openebs-hostpath storageClass.
This one trims the whitespace characters, and removes the newline.
> chore(chart): fix typo in go-template for hostpath-class.yaml and device-class.yaml

- charts/openebs/Chart.yaml
- charts/openebs/templates/legacy/cleanup-webhook.yaml
- charts/openebs/values.yaml
Decided to  not re-use the global `.Values.imagePullSecrets` and instead have a dedicated one under `.Values.cleanup.image.imagePullSecrets` since `.Values.cleanup.image` contains all other image related values for the cleanup image.  Let me know what to think, I'm happy to switch it over to use the global one.
Supersedes #272 
> [stable/openebs] enables imagePullSecrets in cleanup-webhook

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- GOVERNANCE.md
- MAINTAINERS
- README.md
- SECURITY.md
- charts/openebs/Chart.yaml
- charts/openebs/README.md
- charts/openebs/templates/NOTES.txt
- ct.yaml
Updates the version of LVM and ZFS Local PV charts. 
And includes the changes proposed via #237
As a pre-step towards 3.0 and enabling CSI drivers for jiva and
cstor, made the necessary documentation and values.yaml updates.
The premise is that openebs chart will continue its current templates
of ndm and local provisioner, while jiva and cstor will be deprecated
in favor of the corresponding csi charts.
Once 3.0 is released, the recommended way to install cstor, jiva and other
engines would be to enable via this umbrella chart. If there is a strong
use-case for using only one type of engine in a cluster - the user can opt to
install the sub-charts directly.
Trimmed down the configuration options in the README to the commonly used
options.
Also, added Shovan as a maintainer.
Signed-off-by: …
> fix(docs): update helm instructions and versions

- .github/workflows/lint-test.yaml
- .github/workflows/release.yaml
- ct.yaml
Signed-off-by: kmova <kiran.mova@mayadata.io>
Having two branches like main and 2.x pushing the images
doesn't work well with helm chart releaser when users
tend install with latest. A 2.12.5 can be shown as latst
if 2.12.5 chart is released post 3.0.0.
We will have the legacy components continue to maintain
in the main chart itself under the older version.
Update the branch detail to "main"
> chore(ci): rename 2.x to main in ci actions

- charts/openebs/Chart.yaml
- charts/openebs/README.md
- charts/openebs/templates/NOTES.txt
- charts/openebs/templates/localprovisioner/hostpath-class.yaml
- charts/openebs/templates/ndm/daemonset-ndm.yaml
- charts/openebs/values.yaml
Changes:
1. All legacy components (except NDM and localpv-provisioner) image tags set to 2.12.2
2. NDM image tags set to 1.7.0
3. localpv-provisioner image tags set to 3.0.0
4. Updated dependent chart versions to the latest version
5. Bumped chart version and appVersion
6. NDM changes:
i. Ranamed MountChangeDetection to ChangeDetection in DaemonSet yaml and values.yaml
7. OPENEBS_IO_INSTALLER_TYPE is set to "charts-helm" across all components.
8. `--legacy.enabled=false` is now set.
> chore(charts): update helm chart to v3.0.0

- charts/openebs/Chart.yaml
- charts/openebs/values.yaml
This PR updates the openebs chart to use 0.8.0 version of
Dynamic-NFS provisioner
- Updates Char.yaml and values.yaml to point to latest version of NFS
> [stable/openebs]: update openebs chart to use 0.8.0 version of NFS

- charts/openebs/Chart.yaml
This PR updates the openebs chart to use
- 3.0.5 version of jiva-operator
- 3.0.2 version of cstor-operator
> [stable/openebs]: update openebs chart to use latest version of jiva & cstor

- charts/openebs/Chart.yaml
- charts/openebs/README.md
- charts/openebs/values.yaml
Add helm chart version bump for OpenEBS 3.2.0 release
Requires the following PRs to be merged:
- https://github.com/openebs/zfs-localpv/pull/409
- https://github.com/openebs/dynamic-localpv-provisioner/pull/133
- https://github.com/openebs/jiva-operator/pull/184
- https://github.com/openebs/lvm-localpv/pull/185
- https://github.com/openebs/node-disk-manager/pull/671
- https://github.com/openebs/cstor-operators/pull/423
> release(helm-chart): changes for 3.2.0 helm chart release

- CONTRIBUTING.md
Signed-off-by: Abhilash Shetty <abhilash.shetty@datacore.com>
Update contibuter docs to mention that DCO signoff is mandatory
> chore (docs) Update contibuter docs to mention that DCO signoff is mandatory

- charts/openebs/Chart.yaml
- charts/openebs/values.yaml
The image tag used for the Mayastor subchart is incorrect.
> fix(chart): fix mayastor image tag

- README.md
- charts/openebs/Chart.yaml
- charts/openebs/README.md
- charts/openebs/values.yaml
This add release v3.4.1 for the OpenEBS chart. changes:
- mayastor dependency updated to 2.0.1
- values.yaml typo fix for dynamic-nfs-provisioner options
- comment mayastor configuration set to enable the use of subchart options, by default
- remove mayastor base.initContainer and containers configuration, the subchart options will be used by default
> charts(openebs-3.4.1): helm chart for OpenEBS v3.4.1

- lvm-operator.yaml
- versioned/3.8.0/lvm-operator.yaml
Fixes https://github.com/openebs/lvm-localpv/issues/246
The lvm-driver image name is invalid, the image name and the image tag does not have a separating ':'.
The container image names for the lvm-operator have a valid image name now.
> fix(lvm-operator): fix container image name

- .gitignore
- README.md
- charts/openebs/Chart.yaml
- charts/openebs/README.md
- charts/openebs/templates/clusterrole.yaml
- charts/openebs/values.yaml
Ref:
- https://github.com/openebs/cstor-operators/pull/457
- https://github.com/openebs/dynamic-localpv-provisioner/pull/169
- https://github.com/openebs/jiva-operator/pull/219
- https://github.com/openebs/dynamic-nfs-provisioner/pull/178
- https://github.com/openebs/zfs-localpv/pull/488
- https://github.com/openebs/lvm-localpv/pull/278
> feat(charts): bump chart for v3.10.0
