README.md
The instructions have been updated; the new commands install the most up-to-date version of Helm :smiley: cc @kmova
=> Modify instructions so as to install up-to-date versions of Helm

README.md
=> edit for clarity

docs/openebs-operator-0.9.0-RC2.yaml
Added the CRDs names in RBAC authorization for DMaaS.
=> Updated openebs-operator-0.9.0-RC2.yaml

docs/openebs-operator-0.9.0.yaml, docs/openebs-operator.yaml
Updated component labels of admission-server pod.
Also, updated the admission-server image to quay.io
Updated openebs-operator.yaml as per 0.9.0 release.
=> Updated openebs-operator-0.9.0.yaml and openebs-operator.yaml

docs/openebs-operator-1.0.0-RC2.yaml
Updated openebs-operator-1.0.0-RC2.yaml with the missing labels.
=> Updated openebs-operator-1.0.0-RC2.yaml

docs/openebs-operator-1.0.0-RC3.yaml, docs/openebs-operator-1.0.0.yaml, docs/openebs-operator.yaml
Updated openebs-operator-1.0.0-RC3.yaml with node-disk-operator CLEANUP_JOB_IMAGE.
=> Updated openebs-operator-1.0.0-RC3.yaml

docs/openebs-operator-1.0.0-aws.yaml
- Added OpenEBS container 1.0.0 images hosted in Amazon ECR registry for AWS Marketplace listing
=> Added AWS Marketplace Installation

docs/openebs-operator-1.0.0-aws.yaml
Updated the installer type in LocalPV section to "openebs-aws"
=> Updated openebs-operator-1.0.0-aws.yaml

docs/openebs-operator-1.2.0-RC1.yaml
- Add openebs-operator-1.2.0-RC1.yaml for 1.2.0-RC1 release.
=> refactor(openebs-charts): Adding openebs-operator-1.2.0-RC1.yaml

docs/openebs-operator-1.2.0.yaml, docs/openebs-operator.yaml
- Update k8s api version to support latest k8s version
=> refactor (operator) Update k8s api version

docs/openebs-operator-1.3.0-RC2.yaml, docs/openebs-operator-1.3.0-RC3.yaml
Update the YAML with 1.3.0-RC2 tags.
Signed-off-by: kmova <kiran.mova@mayadata.io>
=> feat(install): add operator yaml for 1.3.0-RC2

docs/openebs-operator-1.3.0.yaml, docs/openebs-operator.yaml
- Disabled sparse pool creation by default.
=> refactor (operator) Disable sparse pool creation by default.

docs/openebs-operator-1.3.0-aws.yaml
- Added the manifest file using the scanned v1.3.0 images from the AWS registry
=> Added OpenEBS v1.3.0 manifest for AWS Marketplace Listing

docs/openebs-operator-1.3.0-aws.yaml
=> Fixed AWS ECR location

docs/openebs-operator-1.4.0-RC1.yaml
- Add operator yaml for 1.4.0-RC1
=> feat(install): Add operator yaml for 1.4.0-RC1

docs/openebs-operator-1.4.0-RC2.yaml
- Add operator yaml for 1.4.0-RC2
=> feat(install): Add operator yaml for 1.4.0-RC2

docs/openebs-operator-arm-dev.yaml
Signed-off-by: wangzihao <wangzihao18@huawei.com>
=> fix(arm): fix the arm image name error of node-disk-operator

docs/openebs-operator-1.4.0-aws.yaml
- Add operator YAML for making availability of  1.4 in AWS market place
=> feat(install): Add operator yaml for 1.4.0 in AWS

docs/openebs-operator-1.5.0-RC1.yaml
- Added operator yaml for 1.5.0-RC1
=> feat(install): Add operator yaml for 1.5.0-RC1

docs/openebs-operator-1.5.0-RC2.yaml, docs/openebs-operator-1.5.0.yaml
- Added operator yaml for 1.5.0-RC2
=> feat(install): Add operator yaml for 1.5.0-RC2

docs/openebs-operator.yaml
- Updated openebs-operastor.yaml for 1.5.0 release
=> refactor(install): Update operator yaml for 1.5.0 release

docs/csi-operator-1.5.0-ubuntu-18.04.yaml, docs/csi-operator-1.5.0.yaml, docs/cspc-operator-1.5.0.yaml
- Added cspc-operator-1.5.0.yaml
- Added csi-operator-1.5.0-ubuntu-18.04.yaml
- Added csi-operator-1.5.0.yaml
=> feat(install): Add cspc and csi operator yaml

docs/openebs-operator-1.5.0-RC2.yaml, docs/openebs-operator-1.5.0.yaml
Signed-off-by: nsathyaseelan <sathyaseelan.n@mayadata.io>
- Fixed Typo in operator yaml for 1.5.0 chart
=> fix(operator): Fixed typo in operator yaml for 1.5.0

docs/openebs-lite-helm-values.yaml, docs/openebs-operator-lite.yaml
- Updated openebs-lite-helm-values.yaml
- Updated openebs-operator-lite.yaml
=> refactor(install): Update lite helm values yaml and lite operator yaml

docs/openebs-operator-1.5.0-aws.yaml
- Add openebs operator YAML for making availability of  1.5 in AWS market place
=> feat(install): Add operator YAML for 1.5.0 in AWS

scripts/airgapped/openebs-images-1.5.0.txt, scripts/airgapped/openebs-images.txt, scripts/airgapped/openebs-load-images-1.5.0.sh, scripts/airgapped/openebs-load-images.sh, scripts/airgapped/openebs-save-images-1.5.0.sh, scripts/airgapped/openebs-save-images.sh
- List of the latest container images in openebs-images.txt
- Script to save images and create openebs-images.tar.gz tarball openebs-save-images.sh
- Script to load images to a local registry location from the tarball in openebs-load-images.sh
=> Added Airgapped installation scripts

docs/openebs-operator-1.4.0-aws.yaml
- Update latest ecr registry location as per given from AWS for OpenEBS 1.4 version to work in AWS market place
=> refactor(YAML): Update latest AWS ecr registry location for 1.4

docs/openebs-operator-1.5.0-aws.yaml
- Update latest ecr registry location as per given from AWS for OpenEBS 1.5 version to work in AWS market place
=> refactor(YAML): Update latest AWS ecr registry location for 1.5

docs/openebs-operator-1.6.0-aws.yaml
- Remove extra usage of ":" in NDM image.
=> fix(YAML): Update correct image for NDM pods

docs/openebs-operator-1.7.0-RC1.yaml, docs/openebs-operator-1.7.0-RC2.yaml, docs/openebs-operator-1.7.0.yaml, docs/openebs-operator-lite.yaml
Add operator yaml for 1.7.0 release
- Added operator yaml for 1.7.0-RC1 
- Added operator yaml for 1.7.0-RC2
- Added operator yaml for 1.7.0
- Added operator-lite yaml for 1.7.0
=> feat(install): add operator yaml for 1.7.0

docs/openebs-operator-1.8.0-RC2.yaml
- Add operator yaml file for 1.8.0-RC2 
Signed-off-by: Aman Gupta <aman.gupta@mayadata.io>
=> feat(install): Adding operator yaml file for 1.8.0-RC2

docs/openebs-operator-1.8.0-RC1.yaml
This PR adds the operator YAML required for 1.8.0 changes.
=> feat(install): add operator yaml for 1.8.0

scripts/jiva-tools/README.md
This PR updates data loss condition asking user to check for differences for chains length and used size across replicas.
Signed-off-by: Vitta <vitta@mayadata.io>
=> chore(readme): update in data loss conditions

docs/openebs-operator-1.8.0-aws.yaml
Add openebs operator YAML for making the availability of 1.7.0 in AWS market place
**Notes to the reviewer:**
The following are the changes compared to 1.7 AWS
- Update ECR registry of images with new container group
=> feat(YAML): Add operator YAML for 1.8.0 in AWS market place

docs/csi-operator-1.7.0-ubuntu-18.04.yaml, docs/csi-operator-1.7.0.yaml, docs/csi-operator-1.8.0-ubuntu-18.04.yaml, docs/csi-operator-1.8.0.yaml
commits update 1.7.0 and 1.8.0 version csi operators with correct
release versions which was missed in earlier PR.
=> fix(csi-operator): sync the csi images and crds according to versions

docs/csi-operator-1.9.0-ubuntu-18.04.yaml, docs/csi-operator-1.9.0.yaml, docs/cstor-operator-1.9.0.yaml, docs/openebs-operator-1.9.0.yaml
- update openebs-operator to 1.9.0
- update csi-operator to 1.9.0
- update cstor-operator to 1.9.0
=> chore(operators): update openebs, csi and cstor operators to 1.9.0

docs/openebs-operator-1.9.0.yaml
=> chore(operator): update image tag to 1.9.0 in openebs-operator

docs/openebs-operator-1.9.0.yaml
Signed-off-by: gprasath <giridhara.prasad@mayadata.io>
- Updated ndm tags to v0.4.9
=> refactor(yaml):update image tag of ndm-operator and ndm daemonset

docs/openebs-operator-1.9.0-aws.yaml
Add openebs operator YAML for making the availability of 1.9.0 in AWS market place
**Notes to the reviewer:**
The following are the changes compared to 1.8 AWS
- Update ECR registry of images with new container group
- Updated new commands for livensesProbe for all containers of OpenEBS components
=> feat(YAML): Add operator YAML for 1.9.0 in AWS market place

docs/openebs-operator-lite.yaml
- update version tags to 1.9
- add liveness checks
=> feat(yaml): add operator-lite yaml for 1.9.0

stable/openebs/Chart.yaml, stable/openebs/README.md, stable/openebs/templates/daemonset-ndm.yaml, stable/openebs/values.yaml
- updated README.md
- updated Charts.yaml
- updated values.yaml
- add feature gate to templates/daemonset-ndm.yaml
=> [stable/openebs]: update openebs 1.10-RC1 charts

stable/openebs/Chart.yaml, stable/openebs/README.md, stable/openebs/templates/deployment-maya-apiserver.yaml, stable/openebs/templates/deployment-ndm-operator.yaml, stable/openebs/values.yaml
- update Charts.yaml
- update README.md
=> [stable/openebs]: update charts to 1.10-RC2

stable/openebs/Chart.yaml, stable/openebs/README.md, stable/openebs/templates/daemonset-ndm.yaml, stable/openebs/templates/deployment-admission-server.yaml, stable/openebs/templates/deployment-local-provisioner.yaml, stable/openebs/templates/deployment-maya-apiserver.yaml, stable/openebs/templates/deployment-maya-provisioner.yaml, stable/openebs/templates/deployment-maya-snapshot-operator.yaml, stable/openebs/templates/deployment-ndm-operator.yaml, stable/openebs/values.yaml
- updated Chart.yaml
- updated README.md
- updated values.yaml
- updated templates/daemonset-ndm.yaml
- updated templates/deployment-admission-server.yaml
- updated templates/deployment-local-provisioner.yaml
- updated templates/deployment-maya-apiserver.yaml
- updated templates/deployment-maya-provisioner.yaml
- updated templates/deployment-maya-snapshot-operator.yaml
- updated templates/deployment-ndm-operator.yaml
Cherry picked from [#22372](https://github.com/helm/charts/pull/22372)
=> [stable/openebs] add configurable image registry

docs/openebs-operator-1.10.0-RC1.yaml, docs/openebs-operator-1.10.0-RC2.yaml
- add openebs operator 1.10.0 RC1 yaml
- add openebs operator 1.10.0 RC2 yaml
RC1 & RC2 Yaml for openebs 1.10.0
=> chore(yaml): add openebs operator 1.10.0 yamls

stable/openebs/Chart.yaml, stable/openebs/README.md, stable/openebs/values.yaml
- Updated Chart.yaml
- Updated values.yaml
- Update README
The changes to upstream stable helm will be raised after this PR is merged, and the branch `1.10.0-dev` is merged to master
=> [stable/openebs]: update openebs charts to 1.10.0

docs/openebs-operator-1.10.0.yaml, docs/openebs-operator-lite.yaml
- add operator yaml
- add operator-arm
- add operator-lite
Operator 1.10 yaml
=> chore(yaml): add 1.10.0 operator yaml

stable/openebs/README.md, stable/openebs/templates/daemonset-ndm.yaml, stable/openebs/templates/deployment-admission-server.yaml, stable/openebs/templates/deployment-local-provisioner.yaml, stable/openebs/templates/deployment-maya-apiserver.yaml, stable/openebs/templates/deployment-maya-provisioner.yaml, stable/openebs/templates/deployment-maya-snapshot-operator.yaml, stable/openebs/templates/deployment-ndm-operator.yaml, stable/openebs/values.yaml
=> [stable/openebs]: update image registry in charts

docs/cstor-operator-1.10.0.yaml
=> chore(yaml): add 1.10.0 cstor-operators all in one yaml

docs/csi-operator-1.10.0-ubuntu-18.04.yaml, docs/csi-operator-1.10.0.yaml
=> chore(csi): add csi-operators 1.10.0 yamls

docs/openebs-operator-1.10.0-aws.yaml
- Add openebs operator YAML for making the availability of 1.10.0 in AWS market place
=> feat(YAML): Add operator YAML for 1.10.0 in AWS market place

stable/openebs/Chart.yaml, stable/openebs/README.md
sync with upstream: https://github.com/helm/charts/pull/22445
=> [stable/openebs]: fix README image repository typo

docs/openebs-operator-1.10.0.yaml
update the pull pull policy for:
- localpv-provisioner deployment
- ndm daemonset and
- ndm-operator deployment
=> chore(operator): change imagePull Policy to `IfNotPresent`

.github/workflows/lint-test.yaml
=> chore(ci): bump helm action and chart testing action

stable/openebs/Chart.yaml, stable/openebs/README.md, stable/openebs/templates/cm-node-disk-manager.yaml, stable/openebs/values.yaml
Signed-off-by: fukuta-tatsuya-intec <fukuta_tatsuya@intec.co.jp>
Reflect openebs/openebs#3050
=> [stable/openebs] Add support for configurable filterconfigs.state.

docs/openebs-operator.yaml
Signed-off-by: gprasath <giridhara.prasad@mayadata.io>
- Updated the images to 1.10 and made the file to be in aligned with the latest release. 
=> refactor(yaml): update openebs version to 1.10.0

openebs-ubuntu-setup.yaml
Signed-off-by: Harsh Thakur <harshthakur9030@gmail.com>
=> feat(version): Update yaml to support latest api

scripts/release/create_changelog_pr.sh
=> fix(release): fixing script for changelog generation

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/values.yaml
Update openebs charts to 1.11.0 release
- Updated README
- Updated Chart version
- Updated values.yaml
=> [stable/openebs]: update openebs charts to 1.11.0 release

1.11.0/csi-operator-1.11.0-ubuntu-18.04.yaml, 1.11.0/csi-operator-1.11.0.yaml, 1.11.0/cstor-operator-1.11.0.yaml, csi-operator-ubuntu-18.04.yaml, csi-operator.yaml, cstor-operator.yaml
=> chore(release): add cstor-csi and cstor-operators 1.11.0 yamls

charts/openebs/Chart.yaml, charts/openebs/README.md
- Updated README
- Updated Helm repo location
Due to the deprecation and obsoletion plan of the Helm charts repository this chart has been moved to a new repository. Added additional step to add openebs/openebs chart repo. Updated instructions to use openebs/openebs repository.
=> [openebs/openebs] Update OpenEBS charts instructions

index.md
- Update helm install instructions for OpenEBS charts
- [ x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
=> [openebs/openebs]: Update helm install instructions

1.12.0/csi-operator-1.12.0-RC1.yaml, 1.12.0/csi-operator-1.12.0-RC2.yaml, 1.12.0/cstor-operator-1.12.0-RC1.yaml, 1.12.0/cstor-operator-1.12.0-RC2.yaml
**Why we need this change:**
- Add cstor operator 1.12.0-RC1
- Add csi-operator 1.12.0-RC1
- Add cstor operator 1.12.0-RC2
- Add csi-operator 1.12.0-RC2
=> chore(cstor): add cstor and csi 1.12.0-RC1 and RC2 yamls

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/values.yaml
This PR update openebs charts to 1.12.0 release
- Updated README
- Updated Chart version
- Updated values.yaml
=> [stable/openebs]: update openebs charts to 1.12.0 release

1.12.0/csi-operator-1.12.0-RC1.yaml, 1.12.0/csi-operator-1.12.0-RC2-ubuntu-18.04.yaml, 1.12.0/csi-operator-1.12.0-RC2.yaml, 1.12.0/csi-operator-1.12.0-ubuntu-18.04.yaml, 1.12.0/csi-operator-1.12.0.yaml, 1.12.0/cstor-operator-1.12.0-RC2.yaml, 1.12.0/cstor-operator-1.12.0.yaml, 1.12.0/openebs-operator-1.12.0-RC1.yaml, 1.12.0/openebs-operator-1.12.0-RC2.yaml, csi-operator-ubuntu-18.04.yaml, csi-operator.yaml, cstor-operator.yaml
- cstor operators RC1,RC2 and GA release yamls
- csi operators RC1,RC2 and GA release yamls
- reverting the root mount changes for this release
=> chore(operators): add cstor and csi 1.12.0 operator yamls

openebs-operator-lite-ppc64le.yaml
Signed-off-by: Peeyush Gupta <peeyushgupta91@gmail.com>
This PR adds operator lite yaml for ppc64le.
=> chore(operators): add operator lite yaml for ppc64le

1.12.0/openebs-operator-1.12.0-RC1.yaml, 1.12.0/openebs-operator-1.12.0-RC2.yaml, 1.12.0/openebs-operator-arm-dev.yaml, 1.12.0/openebs-operator-lite.yaml, 1.12.0/openebs-operator-susecaas.yaml, 1.12.0/openebs-operator.yaml, openebs-operator-arm-dev.yaml, openebs-operator-lite.yaml, openebs-operator-susecaas.yaml, openebs-operator.yaml
The following yamls have been updated:
- OpenEBS operator
- OpenEBS Lite
- OpenEBS ARM
- OpenEBS for Suse CaaS
- csi, cstor operators and zfs localPV yamls are not updated in this PR
=> chore(operator, yaml): update operator to 1.12.0

charts/openebs/Chart.yaml, charts/openebs/templates/deployment-admission-server.yaml, charts/openebs/values.yaml
=> [stable/openebs]: add webhook failure policy configurable env

index.md
=> Update OpenEBS charts instructions

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/templates/daemonset-ndm.yaml, charts/openebs/templates/deployment-local-provisioner.yaml, charts/openebs/templates/deployment-maya-provisioner.yaml, charts/openebs/templates/deployment-maya-snapshot-operator.yaml, charts/openebs/values.yaml
This PR updates the openebs charts to 2.0.0 release
- Update README
- Update Charts version
- Update values.yaml
- Update daemonset-ndm.yaml with dev mounts
=> [stable/openebs]: update openebs charts to 2.0.0 release

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/values.yaml
This PR updates the openebs charts to 2.1.0 release
- Update README
- Update Charts version
- Update values.yaml
=> [stable/openebs]: update openebs charts to 2.1.0 release

2.1.0/openebs-operator-2.1.0-aws.yaml, openebs-operator-aws.yaml
- Create and update YAML spec for OpenEBS 2.1.0 in AWS marketplace
- No particular change from previous version. Only image and version update.
=> [openebs]chore(YAML): Create openebs-operator-2.1.0-aws

2.0.0/cstor-operator.yaml, 2.1.0/cstor-operator-2.1.0.yaml, cstor-operator.yaml
=> refact(cstor-operator): add missing upgradetasks CRD

2.0.0/ndm-operator.yaml, 2.0.0/openebs-operator-arm-dev.yaml, 2.0.0/openebs-operator-lite.yaml, 2.0.0/openebs-operator-susecaas.yaml, 2.0.0/openebs-operator.yaml, 2.1.0/ndm-operator-2.1.0.yaml, 2.1.0/openebs-operator-lite.yaml, 2.1.0/openebs-operator-susecaas.yaml, 2.1.0/openebs-operator.yaml, openebs-operator-arm-dev.yaml, openebs-operator-lite.yaml, openebs-operator-susecaas.yaml, openebs-operator.yaml
update ndm version to 0.8.2 which has a fix for a data corruption bug
- updated 2.0.0 operator
- updated 2.1.0 operator (latest)
This is an update for a patch release
=> chore(operator): update ndm version to 0.8.2

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/values.yaml
- update NDM version to 0.8.2 which has the fix for a data corruption bug openebs/openebs#3221
This is a patch release
=> [stable/openebs]:  update NDM version to 0.8.2

scripts/release/check-docker-img-tag.sh, scripts/release/check-openebs-images.sh
add script to check for openebs images in docker hub
=> chore(release): add script to check for images

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/values.yaml
=> [stable/openebs]: update openebs charts to 2.2.0

2.2.0/openebs-operator-2.2.0-aws.yaml, openebs-operator-aws.yaml
- Create and update YAML spec for OpenEBS 2.2.0 in AWS marketplace. Create a new YAML spec file under 2.2.0 folder and updated general openebs-operator-aws yaml spec.
- No particular change from the previous version. Only image and version update.
=> [openebs]chore(YAML): Create openebs-operator-2.2.0-aws.yaml

charts/openebs/Chart.yaml, charts/openebs/README.md
Signed-off-by: Mateusz Gozdek <mateusz@kinvolk.io>
=> Fix typo in README.md

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/values.yaml
- update openebs charts to 2.3.0
- add /dev/ prefix in ndm configmap exclude list
=> [stable/openebs]: update openebs charts to 2.3.0

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/templates/daemonset-ndm.yaml, charts/openebs/templates/deployment-admission-server.yaml, charts/openebs/templates/deployment-local-provisioner.yaml, charts/openebs/templates/deployment-maya-apiserver.yaml, charts/openebs/templates/deployment-maya-provisioner.yaml, charts/openebs/templates/deployment-maya-snapshot-operator.yaml, charts/openebs/templates/deployment-ndm-operator.yaml, charts/openebs/values.yaml
Signed-off-by: Richard Arends <richard.arends@nl.thalesgroup.com>
=> feat(chart): add support for resource limits

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/templates/deployment-maya-provisioner.yaml, charts/openebs/values.yaml
- add env to configure setting node affinity on jiva replica deployments
- update deployment-maya-provisioner.yaml
=> [stable/openebs]: add env to configure setting node affinity

scripts/uninstall/uninstall.sh
- add script to uninstall openebs from the cluster
Uninstall script from openebs/openebs-docs#900
=> chore(doc): add script to perform openebs uninstall

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/templates/daemonset-ndm.yaml, charts/openebs/templates/deployment-local-provisioner.yaml, charts/openebs/templates/deployment-ndm-operator.yaml, charts/openebs/values.yaml
Update charts to 2.5.0
- update ndm daemonset yaml
- update localpv provisioner deployment
=> [stable/openebs]: update openebs charts to 2.5.0

2.5.0/zfs-operator.yaml, zfs-operator.yaml
- update zfs operator with latest snapshotter, provisioner, registrar images
=> chore(operator): update ZFS operator with latest csi images

2.5.0/cstor-operator.yaml, 2.5.0/ndm-operator.yaml, 2.5.0/openebs-operator-lite.yaml, 2.5.0/openebs-operator.yaml, cstor-operator.yaml, ndm-operator.yaml, openebs-operator-lite.yaml, openebs-operator.yaml
=> chore(operator): update operator to use NDM 1.1.1

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/values.yaml
=> [stable/openebs]: update openebs ndm to 1.1.1

scripts/release/openebs-repos.txt
- add local PV and exporter repos
=> chore(release): add new repos to release management

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/values.yaml
=> [stable/openebs]: update openebs to 2.6.0

grafana-charts/README.md, grafana-charts/clustervolumesdashboard.json, grafana-charts/cstorvolumereplicasdashboard.json, grafana-charts/localpvdashboard.json, grafana-charts/storageclassvolumedashboard.json, grafana-charts/storagepoolclaimdashboard.json, grafana-charts/storagepooldashboard.json, grafana-charts/volumetiledviewdashboard.json, grafana-charts/volumeworkloadreportdashboard.json
added OpenEBS tag to the Grafana dashboards
=> added OpenEBS tag to the Grafana dashboards 

grafana-charts/README.md, grafana-charts/storagepoolclaimdashboard.json, grafana-charts/volumeworkloadreportdashboard.json
Signed-off-by: Abhishek Agarwal <abhishek.agarwal@mayadata.io>
Modified README.md file to include the steps required for monitoring OpenEBS pools & volumes for different Prometheus setups. Also removed unwanted links from storagepoolclaim dashboard.
=> Modified README.md file for OpenEBS pools & volumes monitoring

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/templates/cleanup-webhook.yaml, charts/openebs/values.yaml
Fixes: https://github.com/openebs/openebs/issues/3338
=> [stable/openebs]: update openebs charts to 2.7.0

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/templates/cm-node-disk-manager.yaml, charts/openebs/values.yaml
=> [stable/openebs]: update openebs charts to 2.8.0

.github/workflows/release.yaml
=> fix(release): bump chart releaser action to 1.2.0

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/values.yaml
- update Chart version
- update values
=> [stable/openebs]: update openebs charts to 2.9.0

.github/workflows/lint-test.yaml, charts/openebs/Chart.yaml, charts/openebs/values.yaml
Some components and csi-drivers are added as a dependency. This will enable us to install multiple storage engines using this umbrella chart.
openebs-ndm -> https://openebs.github.io/node-disk-manager
localpv-provisioner -> https://openebs.github.io/dynamic-localpv-provisioner
cstor -> https://openebs.github.io/cstor-operators
jiva -> https://openebs.github.io/jiva-operator
zfs-localpv -> https://openebs.github.io/zfs-localpv
Developer doc -> https://docs.google.com/document/d/1RE3rKWnsn3rmzPJ-ZtVCe6NvIH8o_FT2VKoh8UbSYBw
Storage engine specific configuration present as comment.
Migration details present in comment.
```bash
helm install openebs \
--namespace openebs \
--create-namespace \
--version=2.8.0
helm upgrade openebs \
--namespace openebs \
--set ndm.enabled=false \
--set …
```
=> feat(helm chart): updated openebs helm chart to support multiple storage engine installation

index.md
Update steps to install CSI and non CSI components using openebs helm chart.
=> refact(charts): update openebs chart index page

.github/workflows/lint-test.yaml, charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/templates/cleanup-webhook.yaml, charts/openebs/values.yaml
- add LVM local pv chart as a dependency chart of this umbrella chart.
- add a condition on webhook cleanup job
- update dependency map in chart readme.
- update readme on how to install a csi driver using this chart.
=> feat(charts): add lvm local pv chart as a dependency

2.10.0/jiva-operator.yaml, jiva-operator.yaml
This PR updates the jiva-operator with 2.10.1 images
=> chore(operator): update jiva-operator with 2.10.1 images

microk8s-cstor-operator.yaml
Update the microk8s-cstor-operator to 2.10 from 2.7
=> chore(operator-yaml): Update microk8s cstor-operator

2.10.0/hostpath-operator.yaml, 2.10.0/openebs-operator-lite.yaml, 2.10.0/openebs-operator.yaml, hostpath-operator.yaml, openebs-operator-lite.yaml, openebs-operator.yaml
Updated image version for openebs-operator.yaml and openebs-operator-lite.yaml
=> fix(operator-yaml): Update image tag for openebs-operator and openebs-operator-lite

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/templates/daemonset-ndm.yaml, charts/openebs/templates/deployment-ndm-operator.yaml, charts/openebs/values.yaml
- update readme
- update values
- update ndm daemonset template
- update ndm deployment template
=> [stable/openebs]: update charts to 2.11.0

2.11.0/hostpath-operator.yaml, 2.11.0/openebs-operator-lite.yaml, 2.11.0/openebs-operator.yaml, hostpath-operator.yaml, openebs-operator-lite.yaml, openebs-operator.yaml
Ref: https://github.com/openebs/dynamic-localpv-provisioner/issues/71
Depends on https://github.com/openebs/dynamic-localpv-provisioner/pull/73
=> chore(operator-yaml): Update provisioner-localpv image version to 2.11.1

openebs-operator-lite.yaml
This updates the labels and versions for all components, except provisioner-localpv image version.
=> chart(openebs-operator-lite): Update openebs-operator-lite for v2.11.0

2.11.0/nfs-operator.yaml, nfs-operator.yaml
=> feat(stable/nfs-provisioner): add yaml for nfs-provisioner v0.5.0

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/templates/kyverno/allow-capabilities.yaml, charts/openebs/templates/kyverno/allow-host-namespaces.yaml, charts/openebs/templates/kyverno/allow-host-ports.yaml, charts/openebs/templates/kyverno/allow-privilege-escalation.yaml, charts/openebs/templates/kyverno/allow-privileged-containers.yaml, charts/openebs/templates/kyverno/allow-proc-mount.yaml, charts/openebs/templates/kyverno/allow-selinux.yaml, charts/openebs/templates/kyverno/allow-volumes.yaml, charts/openebs/templates/kyverno/require-user-groups.yaml, charts/openebs/values.yaml
Addresses the following issues: openebs/openebs#3385
Addresses the following PR: openebs/openebs#3409
Signed-off-by: Nivedita Prasad niveditaprasad81@gmail.com
=> Kyverno policies

nfs-operator.yaml, versioned/2.12.0/nfs-operator.yaml
=> chore(nfs): operator yaml for nfs-provisioner release 0.6.0 and 0.6.1

lvm-operator.yaml, ndm-operator.yaml
Signed-off-by: Abhishek Agarwal <abhishek.agarwal@mayadata.io>
=> fix(operators): ndm exporter and lvm node driver service endpoint discovery

charts/openebs/Chart.yaml
=> chore(chart): updating nfs-provisioner version to 0.6.1

.github/workflows/lint-test.yaml, .github/workflows/release.yaml
=> chore(ci): update base branch as 2.x

charts/openebs/Chart.yaml
=> chore(helm): update latest chart version of jiva, zfs and lvm 

jiva-operator.yaml, versioned/2.12.0/jiva-operator.yaml
Signed-off-by: shubham <shubham14bajpai@gmail.com>
Cherry-pick for PR https://github.com/openebs/jiva-operator/pull/147
=> fix(jiva-operator): update yaml with custom priorityclasses

charts/openebs/Chart.yaml
=> chore(chart): updating nfs-provisioner chart version to 0.7.1

cstor-operator.yaml, hostpath-operator.yaml, legacy-openebs-operator.yaml, lvm-operator.yaml, ndm-operator.yaml, nfs-operator.yaml, openebs-operator-lite.yaml, openebs-operator-susecaas.yaml, openebs-operator.yaml, versioned/2.12.0/cstor-operator.yaml, versioned/2.12.0/hostpath-operator.yaml, versioned/2.12.0/lvm-operator.yaml, versioned/2.12.0/ndm-operator.yaml, versioned/2.12.0/nfs-operator.yaml, versioned/2.12.0/openebs-operator-lite.yaml, versioned/2.12.0/openebs-operator.yaml, versioned/2.12.0/zfs-operator.yaml, versioned/legacy-v2.12.x/legacy-openebs-operator-ci.yaml, zfs-operator.yaml
Signed-off-by: nsathyaseelan <sathyaseelan.n@mayadata.io>
- This PR updates the image tag for 2.12.0 branch also updated the liveness probe for openebs provisioner deployment
=> fix[operator-yaml]: Updated the image tag and liveness probe for operator yaml

charts/openebs/Chart.yaml, charts/openebs/templates/legacy/deployment-maya-apiserver.yaml, charts/openebs/templates/legacy/deployment-maya-provisioner.yaml, charts/openebs/values.yaml
Signed-off-by: Aamir Shaikh <aameer.shaikh@mayadata.io>
=> fix(charts): update image tag to 2.12.2

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/templates/NOTES.txt, charts/openebs/templates/localprovisioner/deployment-local-provisioner.yaml, charts/openebs/templates/localprovisioner/device-class.yaml, charts/openebs/templates/localprovisioner/hostpath-class.yaml, charts/openebs/templates/ndm/daemonset-ndm.yaml, charts/openebs/values.yaml
The changes in this PR are required for OpenEBS v3.1.0 release.
- Version changes for 3.1.0 release
- Add options as customisation enhancements for localprovisioner (dynamic-localpv-provisioner) (Ref: [openebs/dynamic-localpv-provisioner#102](https://github.com/openebs/dynamic-localpv-provisioner/pull/102), [openebs/dynamic-localpv-provisioner#106](https://github.com/openebs/dynamic-localpv-provisioner/pull/106))
- Add deprecation notice in NOTES.txt file for older localprovisioner flags.
=> release(helm-chart): changes for OpenEBS v3.1.0 helm chart

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/templates/localprovisioner/hostpath-class.yaml, charts/openebs/values.yaml
Add the 3.3.0 helm chart changes
=> release(helm-chart): add helm chart changes for v3.3.0 release

charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/values.yaml
Signed-off-by: Niladri Halder <niladri.halder26@gmail.com>
This adds helm chart changes for OpenEBS v3.4.0 release.
=> release(chart): add helm chart changes for v3.4.0

.github/workflows/lint-test.yaml, README.md, charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/templates/localprovisioner/deployment-local-provisioner.yaml, charts/openebs/templates/localprovisioner/device-class.yaml, charts/openebs/templates/localprovisioner/hostpath-class.yaml, charts/openebs/templates/ndm/cluster-exporter-service.yaml, charts/openebs/templates/ndm/cluster-exporter.yaml, charts/openebs/templates/ndm/cm-node-disk-manager.yaml, charts/openebs/templates/ndm/daemonset-ndm.yaml, charts/openebs/templates/ndm/deployment-ndm-operator.yaml, charts/openebs/templates/ndm/node-exporter-service.yaml, charts/openebs/templates/ndm/node-exporter.yaml, charts/openebs/values.yaml
Signed-off-by: Prateek Chandra <Prateek.Chandra@datacore.com>
Added the ability to install mayastor from openebs helm charts.
=> feat: mayastor as a first class citizen in openebs

charts/openebs/Chart.yaml, charts/openebs/values.yaml
This PR adds changes for OpenEBS 3.5.0.
=> chore(chart): add chart changes for openebs 3.5.0

README.md, charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/values.yaml
Adds helm chart changes for:
- mayastor
- zfs-localpv
- lvm-localpv
- device-localpv
=> feat(charts): add helm chart changes v3.7.0

README.md, charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/values.yaml
This updates the following charts:
- mayastor
- zfs-localpv
- cstor
- lvm-localpv
- jiva
- device-localpv
=> feat(charts): add v3.8.0 helm chart

README.md, charts/openebs/Chart.yaml, charts/openebs/README.md, charts/openebs/values.yaml
This PR adds helm chart updates for mayastor, dynamic-localpv and jiva.
=> feat(charts): helm chart changes for 3.9.0

README.md
=> chore: update link to openebs archive
